{
 "title": "dashboard_Rest-API and Redis",
 "description": "Predefined dashboards to observe any Redis database using Redis Data Source. Requires Grafana 7.1+.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "client_name", "label": "client name", "query": { "query": "label_values(client)" } },
   {
    "name": "max_time",
    "query": {
     "query": "query_result(max(pipeline_start_time))"
    }
   },
   {
    "name": "pip_id",
    "query": {
     "query": "query_result(sum by (pipeline_id) (pipeline_start_time) == $max_time)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last 5 Pipeline Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(pipeline_id)(\n  sum by (pipeline_id) (pipeline_end_time)\n  -\n  sum by (pipeline_id) (pipeline_start_time)\n) * 1000\nAND ON (pipeline_id)\n  topk(5, max by (pipeline_id) (pipeline_start_time))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 5 Pipeline Errors",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pipeline_id)(\n  http_request_total{code=~\"4..|5..\", client=~\"$client_name\"}) \nAND ON (pipeline_id)\ntopk(5, max by (pipeline_id) (pipeline_start_time))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 5 Pipeline Error Rate",
   "type": "bargauge",
   "description": "Percentage of requests resulting in a 5xx status code (server errors) over the last minute.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum by (pipeline_id)(\n  rate(http_request_total{code=~\"4..|5..\", client=~\"$client_name\"}[1m])\n)\n/\nsum by (pipeline_id)(\n  rate(http_request_total{client=~\"$client_name\"}[1m])\n)\n* 100 > 0\n\nAND ON (pipeline_id)\n  topk(5, max by (pipeline_id) (pipeline_start_time))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 5 Pipeline Latency",
   "type": "bargauge",
   "description": "99th Percentile response time in seconds over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pipeline_id) (rate(http_request_duration_bucket{client=~\"$client_name\"}[1m]))) * 1000 > 0\nAND ON (pipeline_id)\ntopk(5, max by (pipeline_id) (pipeline_start_time))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 5 Pipeline Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_id)(\n  http_request_total{client=~\"$client_name\"})\nAND ON (pipeline_id)\ntopk(5, max by (pipeline_id) (pipeline_start_time))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 5 Pipeline Response Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (pipeline_id) (http_request_duration_sum{client=~\"$client_name\"})\n AND ON (pipeline_id)\ntopk(5, max by (pipeline_id) (pipeline_start_time))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  scalar(max(http_request_created{pipeline_id=\"$pip_id\"}))\n  - scalar(pipeline_start_time{pipeline_id=\"$pip_id\"})\n) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_id)(\n  (http_request_total{code=~\"4..|5..\", client=~\"$client_name\", pipeline_id=\"$pip_id\"}) > 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Error Rate",
   "type": "stat",
   "description": "Percentage of requests resulting in a 5xx status code (server errors) over the last minute.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_id)(\n  rate(http_request_total{code=~\"4..|5..\", client=~\"$client_name\",pipeline_id=\"$pip_id\"}[1m])\n)\n/\nsum by (pipeline_id)(\n  rate(http_request_total{client=~\"$client_name\",pipeline_id=\"$pip_id\"}[1m])\n)\n* 100 > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Latency (P99)",
   "type": "stat",
   "description": "99th Percentile response time in seconds over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pipeline_id) (rate(http_request_duration_bucket{client=~\"$client_name\",pipeline_id=\"$pip_id\"}[1m]))) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline_id)(\n  http_request_total{client=~\"$client_name\",pipeline_id=\"$pip_id\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Response Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (pipeline_id) (http_request_duration_sum{client=~\"$client_name\",pipeline_id=\"$pip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Error Rate",
   "type": "timeseries",
   "description": "Calculating Request Error Rates",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (client)(rate(http_request_duration_count{code=~\"4..|5..\", client=~\"$client_name\"}[1m]))\n  /\n  sum by (client)(rate(http_request_duration_count{client=~\"$client_name\"}[1m]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client requests Rate",
   "type": "timeseries",
   "description": "HTTP requests rate",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(http_request_duration_count{client=~\"$client_name\"}[1m])) * 60 > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Latency (Response Time)",
   "type": "timeseries",
   "description": "95th Percentile response time in seconds over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, client) (rate(http_request_duration_bucket{client=~\"$client_name\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Error Count",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path, code)(\n  (http_request_total{code=~\"4..|5..\", client=~\"$client_name\"})\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Average Requests Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_request_duration_sum{exported_job=\"http_metrics_job\",client=~\"$client_name\"} / http_request_duration_count{exported_job=\"http_metrics_job\",client=~\"$client_name\"}) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Requests Count",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_total{exported_job=\"http_metrics_job\",client=~\"$client_name\"}) by (client,path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(pipeline_id)(\n  sum by (pipeline_id) (pipeline_end_time)\n  -\n  sum by (pipeline_id) (pipeline_start_time)\n) * 1000\nAND ON (pipeline_id)\n  topk(5, max by (pipeline_id) (pipeline_start_time))",
     "legendFormat": "__auto"
    },
    {
     "expr": "  topk(5, max by (pipeline_id) (pipeline_start_time) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "redis" },
  {
   "title": "Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "command": "info",
     "section": "stats",
     "streamingCapacity": 1000,
     "streamingInterval": 1000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "command": "info",
     "section": "clients",
     "streamingCapacity": 1000,
     "streamingInterval": 1000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "info", "section": "server", "streamingCapacity": 1, "type": "command" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "info", "section": "server", "streamingCapacity": 1, "type": "command" }
   ]
  },
  {
   "title": "Number of Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "query": "dbsize", "streamingCapacity": 1000, "streamingInterval": 1000, "type": "cli" }
   ]
  },
  {
   "title": "Keys Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "command": "info",
     "section": "stats",
     "streamingCapacity": 1000,
     "streamingInterval": 1000,
     "type": "command"
    }
   ]
  }
 ]
}